// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideos(arg1) {
  return window['go']['main']['App']['DownloadVideos'](arg1);
}

export function SetOutputDir() {
  return window['go']['main']['App']['SetOutputDir']();
}
