// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideos(arg1:string):Promise<void>;

export function SetOutputDir():Promise<string>;
